const fs=require('fs');const path=require('path');const f=path.join(process.cwd(),'app','page.tsx');let s=fs.readFileSync(f,'utf8');
const r=(a,b,n)=>{if(!s.includes(a))throw new Error('account patch target not found: '+n);s=s.replace(a,b)};

r('const MENU = ["🏠 홈", "📤 숙제 내기", "📥 숙제 제출", "❓ 질문게시판", "📅 캘린더", "💬 개인채팅", "🤖 AI 학습도우미", "🔔 알림"];','const MENU = ["🏠 홈", "📤 숙제 내기", "📥 숙제 제출", "⏰ 밀린 숙제", "❓ 질문게시판", "📅 캘린더", "💬 개인채팅", "🤖 AI 학습도우미", "🔔 알림"];','menu');
r('const[aiText,setAiText]=useState(""),[aiFiles,setAiFiles]=useState<File[]>([]),[aiMessages,setAiMessages]=useState<{role:string;content:string}[]>([]),[aiBusy,setAiBusy]=useState(false),[month,setMonth]=useState(new Date()),[calendar,setCalendar]=useState<any[]>([]),[progress,setProgress]=useState("");','const[aiText,setAiText]=useState(""),[aiFiles,setAiFiles]=useState<File[]>([]),[aiMessages,setAiMessages]=useState<{role:string;content:string}[]>([]),[aiBusy,setAiBusy]=useState(false),[month,setMonth]=useState(new Date()),[calendar,setCalendar]=useState<any[]>([]),[progress,setProgress]=useState("");\n const[accountOpen,setAccountOpen]=useState(false),[accountEdit,setAccountEdit]=useState(false),[accountName,setAccountName]=useState(""),[accountSubject,setAccountSubject]=useState(SUBJECTS[0]),[darkMode,setDarkMode]=useState(false),[dailyEnglishState,setDailyEnglishState]=useState<[string,string]>(["오늘의 영어 문장","문장을 불러오는 중..."]);','state');

r('{active==="🏠 홈"&&<><section className="hero"><h2>오늘의 영어 문장</h2><div className="daily-english"><b>{dailyEnglish[0]}</b><p>{dailyEnglish[1]}</p></div></section>','{active==="🏠 홈"&&<><section className="hero"><h2>오늘의 영어 문장</h2><div className="daily-english"><b>{dailyEnglishState[0]}</b><p>{dailyEnglishState[1]}</p></div></section>','daily placeholder');

r('const me=state?.me||"",users=arr(state,["users","members"])','useEffect(()=>{if(!auth)return;fetch("/daily-english.json",{cache:"no-store"}).then(r=>r.json()).then(list=>{if(!Array.isArray(list)||!list.length)return;const day=Math.floor((Date.now()-new Date(new Date().getFullYear(),0,0).getTime())/86400000);const x=list[day%list.length];if(Array.isArray(x))setDailyEnglishState([String(x[0]),String(x[1])])}).catch(()=>{})},[auth]);useEffect(()=>{if(typeof window!=="undefined"){const v=window.localStorage.getItem("mentor-dark-mode")==="1";setDarkMode(v);document.documentElement.classList.toggle("dark",v)}},[]);useEffect(()=>{if(typeof window!=="undefined"){window.localStorage.setItem("mentor-dark-mode",darkMode?"1":"0");document.documentElement.classList.toggle("dark",darkMode)}},[darkMode]);\n const me=state?.me||"",users=arr(state,["users","members"])','effects');

r('<div className="topbar-right"><div className="user-pill">{currentUser?userLabel(currentUser):""}</div><button className="icon-btn" onClick={()=>setActive("🔔 알림")}>🔔 {notifications.filter((n:any)=>!n.read).length}</button></div>','<div className="topbar-right"><button className="theme-toggle" onClick={()=>setDarkMode(v=>!v)}>{darkMode?"☀️":"🌙"}</button><div className="account-wrap"><button className="user-pill user-button" onClick={()=>{setAccountOpen(v=>!v);setAccountEdit(false);setAccountName(currentUser?.name||"");setAccountSubject(currentUser?.subject||SUBJECTS[0])}}>{currentUser?userLabel(currentUser):""}</button>{accountOpen&&<div className="account-menu"><button onClick={()=>setAccountEdit(true)}>⚙ 계정 정보</button><button onClick={()=>action("app_logout").then(()=>location.reload())}>↪ 로그아웃</button><button className="danger-text" onClick={()=>{if(window.confirm("정말 탈퇴할까요?"))rpc("app_delete_account").then(()=>location.reload()).catch((e:any)=>toast(e.message))}}>탈퇴</button></div>}</div><button className="icon-btn" onClick={()=>setActive("🔔 알림")}>🔔 {notifications.filter((n:any)=>!n.read).length}</button></div>','header');

const end='</main></div>;';
if(!s.includes(end))throw new Error('account patch target not found: end');
s=s.replace(end,`{accountEdit&&<div className="modal-backdrop" onClick={()=>setAccountEdit(false)}><div className="modal-card account-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAccountEdit(false)}>×</button><h2>계정 정보 수정</h2><div className="smalltext">아이디</div><div className="account-readonly">{currentUser?.id||""}</div><input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="이름"/><select value={accountSubject} onChange={e=>setAccountSubject(e.target.value)}>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select><div className="task-actions"><button className="primary" onClick={updateAccount}>저장</button><button className="outline" onClick={()=>setAccountEdit(false)}>취소</button></div></div></div>}${end}`);

r('async function createTask(e:FormEvent)','async function updateAccount(){await rpc("app_update_account",{p_name:accountName.trim(),p_subject:accountSubject});await refresh();setAccountEdit(false);setAccountOpen(false)}\n async function createTask(e:FormEvent)','account helper');
fs.writeFileSync(f,s);
