const fs=require('fs');
const path=require('path');
const file=path.join(process.cwd(),'app','page.tsx');
let s=fs.readFileSync(file,'utf8');

const homeRe=/\{active==="🏠 홈"&&[\s\S]*?\}\s*\{active==="📤 숙제 내기"/;
const home=`{active==="🏠 홈"&&<><section className="hero"><h2>오늘도 차근차근, 공부를 이어가요 👋</h2><p>숙제와 질문, 일정과 개인채팅을 한곳에서 관리하세요.</p></section><div className="grid"><Stat label="제출할 숙제" value={assignedTasks.length} icon="📝"/><Stat label="내가 낸 숙제" value={createdTasks.length} icon="📤"/><Stat label="완료" value={assignedTasks.filter((t:any)=>(t.statusByUser?.[me]||"미제출")==="완료").length} icon="✅"/><Stat label="새 알림" value={notifications.filter((n:any)=>!n.read).length} icon="🔔"/></div><section className="card"><div className="section-title"><div><h2>⏰ 가장 임박한 숙제</h2><p className="muted">마감일이 가까운 숙제 3개입니다.</p></div><button className="outline" onClick={()=>setActive("📥 숙제 제출")}>숙제 제출로 이동</button></div><UpcomingTasks tasks={assignedTasks} users={users} me={me}/></section></>} {active==="📤 숙제 내기"`;
if(!homeRe.test(s))throw new Error('home block not found');
s=s.replace(homeRe,home);

const submitRe=/function TaskSubmitList\([\s\S]*?\nfunction CreatedTaskList/;
const submit=`function TaskSubmitList({tasks,me,files,setFiles,memos,setMemos,submit,users,refresh}:{tasks:any[];me:string;files:Record<string,File[]>;setFiles:(v:Record<string,File[]>)=>void;memos:Record<string,string>;setMemos:(v:Record<string,string>)=>void;submit:(t:any)=>void;users:any[];refresh:()=>Promise<void>}){const[drafts,setDrafts]=useState<Record<string,string>>({});async function addComment(t:any){const text=(drafts[String(t.id)]||'').trim();if(!text)return;try{await rpc("app_add_comment",{p_type:"task",p_target:Number(t.id),p_text:text,p_files:[]});setDrafts(v=>({...v,[String(t.id)]:''}));await refresh()}catch(e:any){window.alert(e?.message||"댓글 등록에 실패했습니다.")}}return <section className="card">{tasks.length?tasks.map((t:any)=>{const status=t.statusByUser?.[me]||"미제출";return <article className="task task-large" key={t.id}><div className="task-main"><div className="section-title"><div><b>{t.title}</b><div className="muted smalltext">과목: {t.subject||"-"} · 출제자: {userLabel(users.find((u:any)=>u.id===t.creatorId))} · 마감: {t.due||"-"}</div></div><span className={"badge "+statusClass(status)}>{status}</span></div><div className="task-desc">{t.desc||t.description||"내용 없음"}</div><AttachmentList attachments={t.attachments}/>{t.feedbackByUser?.[me]&&<div className="feedback">피드백: {t.feedbackByUser[me]}</div>}{status!=="완료"&&<><textarea placeholder="제출 메모(선택)" value={memos[String(t.id)]||""} onChange={e=>setMemos({...memos,[String(t.id)]:e.target.value})}/><FilePicker files={files[String(t.id)]||[]} setFiles={f=>setFiles({...files,[String(t.id)]:f})}/><button className="outline" onClick={()=>submit(t)}>제출하기</button></>}<div className="comments-block"><b>댓글</b>{(t.comments||[]).length?(t.comments||[]).map((c:any)=><div className="comment" key={c.id}>↳ {userLabel(users.find((u:any)=>u.id===c.userId))}: {c.text}</div>):<div className="muted smalltext">아직 댓글이 없습니다.</div>}<input value={drafts[String(t.id)]||""} placeholder="댓글 작성 후 Enter" onChange={e=>setDrafts({...drafts,[String(t.id)]:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();addComment(t)}}}/></div></div></article>}) : <Empty text="현재 나에게 배정된 숙제가 없습니다."/>}</section>}
function CreatedTaskList`;
if(!submitRe.test(s))throw new Error('submit list block not found');
s=s.replace(submitRe,submit);

const createdRe=/function CreatedTaskList\([\s\S]*?\nfunction Calendar/;
const created=`function CreatedTaskList({tasks,users,refresh}:{tasks:any[];users:any[];refresh:()=>Promise<void>}){const[drafts,setDrafts]=useState<Record<string,string>>({});async function addComment(t:any){const text=(drafts[String(t.id)]||'').trim();if(!text)return;try{await rpc("app_add_comment",{p_type:"task",p_target:Number(t.id),p_text:text,p_files:[]});setDrafts(v=>({...v,[String(t.id)]:''}));await refresh()}catch(e:any){window.alert(e?.message||"댓글 등록에 실패했습니다.")}}return <section className="card">{tasks.length?tasks.map((t:any)=>{const ids=Array.isArray(t.assigneeIds)?t.assigneeIds:[];return <details className="created-task" key={t.id}><summary className="created-task-summary"><div><b>{t.title}</b><div className="muted smalltext">과목: {t.subject||"-"} · 출제자: {userLabel(users.find((u:any)=>u.id===t.creatorId))} · 마감: {t.due||"-"}</div></div></summary><div className="created-task-detail"><div className="task-desc">{t.desc||t.description||"내용 없음"}</div><AttachmentList attachments={t.attachments}/><div className="smalltext"><b>수행 대상 및 상태</b></div>{ids.length?ids.map((uid:string)=>{const u=users.find((x:any)=>String(x.id)===String(uid));const status=t.statusByUser?.[uid]||t.statusByUser?.[String(uid)]||"미제출";return <div className="assignee-status" key={uid}><span>☐ {u?u.name+" ("+u.id+")":uid}</span><span className={"badge "+statusClass(status)}>{status}</span>{t.memoByUser?.[uid]&&<span className="muted">메모: {t.memoByUser[uid]}</span>}{t.submissionAttachments?.[uid]&&<AttachmentList attachments={t.submissionAttachments[uid]}/>}</div>;}):<div className="muted smalltext">☐ 수행 대상 미지정</div>}<div className="comments-block"><b>댓글</b>{(t.comments||[]).length?(t.comments||[]).map((c:any)=><div className="comment" key={c.id}>↳ {userLabel(users.find((u:any)=>u.id===c.userId))}: {c.text}</div>):<div className="muted smalltext">아직 댓글이 없습니다.</div>}<input value={drafts[String(t.id)]||""} placeholder="댓글 작성 후 Enter" onChange={e=>setDrafts({...drafts,[String(t.id)]:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();addComment(t)}}}/></div></div></details>):<Empty text="내가 낸 숙제가 없습니다."/>}</section>}
function Calendar`;
if(!createdRe.test(s))throw new Error('created task block not found');
s=s.replace(createdRe,created);

const calendarRe=/function Calendar\([\s\S]*?\nfunction Chat/;
const calendar=`function Calendar({month,setMonth,events,users}:{month:Date;setMonth:(d:Date)=>void;events:any[];users:any[]}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const[selected,setSelected]=useState<any|null>(null);return <><section className="card calendar"><div className="cal-head"><button onClick={()=>setMonth(new Date(y,m-1,1))}>‹</button><h2>{y}년 {m+1}월</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}>›</button></div><div className="week">{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:first+days},(_,i)=>i<first?null:i-first+1).map((d,i)=><div className="day" key={i}>{d&&<><span>{d}</span>{events.filter((e:any)=>String(e.due||e.date||"").endsWith("-"+String(d).padStart(2,"0"))).slice(0,3).map((e:any,j:number)=><button type="button" className="calendar-event" key={e.id||j} onClick={()=>setSelected(e)}>{e.title||"일정"}</button>)}</>}</div>)}</div></section>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><h2>{selected.title||"숙제"}</h2><div className="info-row"><span>과목</span><b>{selected.subject||"-"}</b></div><div className="info-row"><span>출제자</span><b>{userLabel(users.find((u:any)=>u.id===selected.creatorId))}</b></div><div className="info-row"><span>마감</span><b>{selected.due||"-"}</b></div>{selected.status&&<div className="info-row"><span>내 상태</span><b>{selected.status}</b></div>}<div className="task-desc">{selected.description||"내용 없음"}</div><button className="primary" onClick={()=>setSelected(null)}>닫기</button></div></div>}</>}
function Chat`;
if(!calendarRe.test(s))throw new Error('calendar block not found');
s=s.replace(calendarRe,calendar);

s=s.replace('<CreatedTaskList tasks={createdTasks} users={users}/>','<CreatedTaskList tasks={createdTasks} users={users} refresh={refresh}/>');
s=s.replace('<Calendar month={month} setMonth={month} events={calendar}/>','<Calendar month={month} setMonth={month} events={calendar} users={users}/>');
s=s.replace('<Calendar month={month} setMonth={month} events={calendar}/>','<Calendar month={month} setMonth={month} events={calendar} users={users}/>');
s=s.replace('<TaskSubmitList tasks={assignedTasks} me={me} files={submitFiles} setFiles={setSubmitFiles} memos={submitMemo} setMemos={setSubmitMemo} submit={submitTask} users={users}/>','<TaskSubmitList tasks={assignedTasks} me={me} files={submitFiles} setFiles={setSubmitFiles} memos={submitMemo} setMemos={setSubmitMemo} submit={submitTask} users={users} refresh={refresh}/>');
s=s.replace('<Calendar month={month} setMonth={month} events={calendar} users={users}/>','<Calendar month={month} setMonth={month} events={calendar} users={users}/>');
s=s.replace('{(q.comments||[]).map((c:any)=><div className="comment" key={c.id}>↳ {c.name||c.user_id}: {c.body}</div>)}','{(q.comments||[]).map((c:any)=><div className="comment" key={c.id}>↳ {userLabel(users.find((u:any)=>u.id===c.userId))}: {c.text}</div>)}');

const upcoming=`function UpcomingTasks({tasks,users,me}:{tasks:any[];users:any[];me:string}){const list=[...tasks].filter((t:any)=>t.due).sort((a:any,b:any)=>String(a.due).localeCompare(String(b.due))).slice(0,3);return list.length?<div className="upcoming-list">{list.map((t:any)=>{const status=t.statusByUser?.[me]||"미제출";return <div className="upcoming-item" key={t.id}><div><b>{t.title}</b><div className="muted smalltext">{t.subject||"-"} · {t.due}</div><div className="muted smalltext">출제자: {userLabel(users.find((u:any)=>u.id===t.creatorId))}</div></div><span className={"badge "+statusClass(status)}>{status}</span></div>})}</div>:<Empty text="마감일이 지정된 숙제가 없습니다."/>}\n`;
if(!s.includes('function UpcomingTasks'))s=s.replace('function Stat(',upcoming+'function Stat(');

const assertions=[['function UpcomingTasks','home upcoming'],['수행 대상 및 상태','assignee display'],['수행 대상 미지정','unassigned fallback'],['function TaskSubmitList','task comments'],['app_add_comment','comment rpc'],['function Calendar','calendar'],['modal-backdrop','calendar modal'],['c.userId','comment author mapping']];
for(const [needle,label] of assertions)if(!s.includes(needle))throw new Error('missing '+label);
fs.writeFileSync(file,s);
