const fs=require('fs'),path=require('path');const f=path.join(process.cwd(),'app','page.tsx');let s=fs.readFileSync(f,'utf8');
if(!s.includes('function showEditDialog')){const helper=`function showNotice(title,message){const old=document.getElementById('app-modal-notice');if(old)old.remove();const root=document.createElement('div');root.id='app-modal-notice';root.className='app-modal-backdrop';root.innerHTML='<div class="app-modal-card"><h2>'+title+'</h2><p>'+message+'</p><div class="app-modal-actions"><button class="primary">확인</button></div></div>';document.body.appendChild(root);root.querySelector('button').onclick=()=>root.remove()}
function showConfirm(title,message){return new Promise(resolve=>{const old=document.getElementById('app-modal-confirm');if(old)old.remove();const root=document.createElement('div');root.id='app-modal-confirm';root.className='app-modal-backdrop';root.innerHTML='<div class="app-modal-card"><h2>'+title+'</h2><p>'+message+'</p><div class="app-modal-actions"><button class="outline">취소</button><button class="primary danger-confirm">삭제</button></div></div>';document.body.appendChild(root);const done=(v)=>{root.remove();resolve(v)};root.querySelector('.outline').onclick=()=>done(false);root.querySelector('.danger-confirm').onclick=()=>done(true)})}
function showEditDialog(title,fields,onSave){const root=document.createElement('div');root.className='app-modal-backdrop';const card=document.createElement('div');card.className='app-modal-card edit-modal-card';const h=document.createElement('h2');h.textContent=title;card.appendChild(h);const vals={};fields.forEach(x=>{const lab=document.createElement('label');lab.textContent=x.label;let el;if(x.type==='textarea'){el=document.createElement('textarea')}else if(x.type==='date'){el=document.createElement('input');el.type='date'}else if(x.type==='files'){el=document.createElement('input');el.type='file';el.multiple=true}else if(x.type==='multiselect'){el=document.createElement('select');el.multiple=true;el.size=Math.min(7,Math.max(4,(x.options||[]).length));(x.options||[]).forEach(o=>{const op=document.createElement('option');op.value=String(o.value);op.textContent=String(o.label);op.selected=(x.value||[]).includes(String(o.value));el.appendChild(op)})}else{el=document.createElement('input');el.type='text'}if(x.type!=='multiselect'&&x.type!=='files')el.value=x.value||'';lab.appendChild(el);card.appendChild(lab);vals[x.key]=el});const actions=document.createElement('div');actions.className='app-modal-actions';const cancel=document.createElement('button');cancel.className='outline';cancel.textContent='취소';const save=document.createElement('button');save.className='primary';save.textContent='저장';actions.append(cancel,save);card.appendChild(actions);root.appendChild(card);document.body.appendChild(root);cancel.onclick=()=>root.remove();save.onclick=async()=>{save.disabled=true;try{const out={};for(const k of Object.keys(vals)){const v=vals[k];if(v.type==='file'){const fs=Array.from(v.files||[]);validateFiles(fs);out[k]=fs.length?await uploadFiles(fs):[]}else if(v.multiple&&v.tagName==='SELECT'){out[k]=Array.from(v.selectedOptions||[]).map(o=>String(o.value))}else out[k]=v.value}await onSave(out);root.remove()}catch(e){showNotice('수정 실패',e&&e.message||'수정에 실패했습니다.');save.disabled=false}}}
`;s=s.replace('export default function Home(){',helper+'export default function Home(){')}
s=s.replace('const x=window.prompt("댓글을 수정하세요.",c.text||c.body||"");if(x!==null){await rpc("app_update_comment",{p_comment:Number(c.id),p_text:x,p_files:(c.attachments||[]).map((a:any)=>a.id));await refresh?.()}}','showEditDialog("댓글 수정",[{key:"text",label:"댓글 내용",type:"textarea",value:c.text||c.body||""},{key:"files",label:"첨부파일",type:"files"}],async v=>{await rpc("app_update_comment",{p_comment:Number(c.id),p_text:v.text,p_files:[...(c.attachments||[]).map((a:any)=>a.id),...(v.files||[])]});await refresh?.()})');
s=s.replace('if(window.confirm("댓글을 삭제할까요?")){await rpc("app_delete_comment",{p_comment:Number(c.id)});await refresh?.()}','if(await showConfirm("댓글 삭제","이 댓글을 삭제할까요?")){await rpc("app_delete_comment",{p_comment:Number(c.id)});await refresh?.()}');
s=s.replace('if(window.confirm("댓글을 삭제할까요?"))return;await rpc("app_delete_comment",{p_comment:Number(c.id)});','if(!(await showConfirm("댓글 삭제","이 댓글을 삭제할까요?")))return;await rpc("app_delete_comment",{p_comment:Number(c.id)});');
s=s.replace('if(window.confirm("메시지를 삭제할까요?")){await rpc("app_delete_message",{p_message:Number(m.id)});location.reload()}}','if(await showConfirm("메시지 삭제","이 메시지를 삭제할까요?")){await rpc("app_delete_message",{p_message:Number(m.id)});location.reload()}}');
s=s.replace('if(window.confirm("숙제를 삭제할까요?")){await rpc("app_delete_task",{p_task:Number(t.id)});await refresh?.()}','if(await showConfirm("숙제 삭제","이 숙제를 삭제할까요?")){await rpc("app_delete_task",{p_task:Number(t.id)});await refresh?.()}');
s=s.replace('if(window.confirm("질문을 삭제할까요?"))await action("app_delete_question",{p_question:Number(q.id)})','if(await showConfirm("질문 삭제","이 질문을 삭제할까요?"))await action("app_delete_question",{p_question:Number(q.id)})');
s=s.replace('if(window.confirm("제출을 삭제할까요?")){await rpc("app_delete_submission",{p_task:Number(t.id)});window.location.reload()}}','if(await showConfirm("제출 삭제","이 제출을 삭제할까요?")){await rpc("app_delete_submission",{p_task:Number(t.id)});window.location.reload()}}');
s=s.replace('const title=window.prompt("숙제 제목",t.title||"");if(title===null)return;const desc=window.prompt("숙제 내용",t.desc||t.description||"");if(desc===null)return;const due=window.prompt("마감일 YYYY-MM-DD",t.due||"");if(due===null)return;await rpc("app_update_task",{p_task:Number(t.id),p_title:title,p_desc:desc,p_due:due||null,p_assignees:t.assigneeIds||[],p_files:(t.attachments||[]).map((a:any)=>a.id));await refresh?.()','showEditDialog("숙제 수정",[{key:"title",label:"숙제 제목",value:t.title||""},{key:"desc",label:"숙제 내용",type:"textarea",value:t.desc||t.description||""},{key:"due",label:"마감일",type:"date",value:t.due||""},{key:"assignees",label:"수행 대상",type:"multiselect",value:(t.assigneeIds||[]).map(x=>String(x)),options:users.filter(u=>u.id!==me).map(u=>({value:String(u.id),label:userLabel(u)}))},{key:"files",label:"첨부파일 추가",type:"files"}],async v=>{await rpc("app_update_task",{p_task:Number(t.id),p_title:v.title,p_desc:v.desc,p_due:v.due||null,p_assignees:v.assignees||[],p_files:[...(t.attachments||[]).map(a=>a.id),...(v.files||[])]});await refresh?.()})');
s=s.replace('const title=window.prompt("질문 제목",q.title||"");if(title===null)return;const body=window.prompt("질문 내용",q.body||"");if(body===null)return;await action("app_update_question",{p_question:Number(q.id),p_subject:q.subject||"전체",p_title:title,p_body:body,p_files:(q.attachments||[]).map((a:any)=>a.id)})','showEditDialog("질문 수정",[{key:"title",label:"질문 제목",value:q.title||""},{key:"body",label:"질문 내용",type:"textarea",value:q.body||""},{key:"files",label:"첨부파일 추가",type:"files"}],async v=>{await action("app_update_question",{p_question:Number(q.id),p_subject:q.subject||"전체",p_title:v.title,p_body:v.body,p_files:[...(q.attachments||[]).map(a=>a.id),...(v.files||[])]})})');
s=s.replace('const x=window.prompt("메시지를 수정하세요.",m.text||m.body||"");if(x!==null){await rpc("app_update_message",{p_message:Number(m.id),p_text:x,p_files:(m.attachments||[]).map((a:any)=>a.id));location.reload()}}','showEditDialog("메시지 수정",[{key:"text",label:"메시지 내용",type:"textarea",value:m.text||m.body||""},{key:"files",label:"첨부파일 추가",type:"files"}],async v=>{await rpc("app_update_message",{p_message:Number(m.id),p_text:v.text,p_files:[...(m.attachments||[]).map(a=>a.id),...(v.files||[])]});location.reload()})');
fs.writeFileSync(f,s);
