const fs=require('fs'),path=require('path');const f=path.join(process.cwd(),'app','page.tsx');let s=fs.readFileSync(f,'utf8');
if(!s.includes('function showEditDialog')){
const helper=`function showEditDialog(title,fields,onSave){const dlg=document.createElement('dialog');dlg.className='edit-dialog-native';const wrap=document.createElement('div');wrap.innerHTML='<h2>'+title+'</h2>';const vals={};fields.forEach((x)=>{const lab=document.createElement('label');lab.textContent=x.label;let el;if(x.type==='textarea')el=document.createElement('textarea');else if(x.type==='select'){el=document.createElement('select');(x.options||[]).forEach(o=>{const op=document.createElement('option');op.value=o;op.textContent=o;el.appendChild(op)})}else{el=document.createElement('input');el.type=x.type||'text'}el.value=x.value||'';el.style.width='100%';el.style.boxSizing='border-box';el.style.margin='6px 0 12px';lab.appendChild(el);wrap.appendChild(lab);vals[x.key]=el});const row=document.createElement('div');const save=document.createElement('button');save.textContent='저장';const cancel=document.createElement('button');cancel.textContent='취소';row.append(save,cancel);wrap.appendChild(row);dlg.appendChild(wrap);document.body.appendChild(dlg);cancel.onclick=()=>{dlg.close();dlg.remove()};save.onclick=async()=>{save.disabled=true;try{await onSave(Object.fromEntries(Object.entries(vals).map(([k,v])=>[k,v.value])));dlg.close();dlg.remove()}catch(e){alert(e&&e.message||'수정에 실패했습니다.');save.disabled=false}};dlg.showModal()}
`;
s=s.replace('function Home(){',helper+'function Home(){');
}
s=s.replace('const x=window.prompt("댓글을 수정하세요.",c.text||c.body||"");if(x!==null){await rpc("app_update_comment",{p_comment:Number(c.id),p_text:x,p_files:(c.attachments||[]).map((a:any)=>a.id));await refresh?.()}}','showEditDialog("댓글 수정",[{key:"text",label:"댓글 내용",type:"textarea",value:c.text||c.body||""}],async v=>{await rpc("app_update_comment",{p_comment:Number(c.id),p_text:v.text,p_files:(c.attachments||[]).map((a:any)=>a.id)});await refresh?.()})');
s=s.replace('const title=window.prompt("숙제 제목",t.title||"");if(title===null)return;const desc=window.prompt("숙제 내용",t.desc||t.description||"");if(desc===null)return;const due=window.prompt("마감일 YYYY-MM-DD",t.due||"");if(due===null)return;await rpc("app_update_task",{p_task:Number(t.id),p_title:title,p_desc:desc,p_due:due||null,p_assignees:t.assigneeIds||[],p_files:(t.attachments||[]).map((a:any)=>a.id)});await refresh?.()','showEditDialog("숙제 수정",[{key:"title",label:"숙제 제목",value:t.title||""},{key:"desc",label:"숙제 내용",type:"textarea",value:t.desc||t.description||""},{key:"due",label:"마감일",type:"date",value:t.due||""}],async v=>{await rpc("app_update_task",{p_task:Number(t.id),p_title:v.title,p_desc:v.desc,p_due:v.due||null,p_assignees:t.assigneeIds||[],p_files:(t.attachments||[]).map((a:any)=>a.id)});await refresh?.()})');
s=s.replace('const title=window.prompt("질문 제목",q.title||"");if(title===null)return;const body=window.prompt("질문 내용",q.body||"");if(body===null)return;await action("app_update_question",{p_question:Number(q.id),p_subject:q.subject||"전체",p_title:title,p_body:body,p_files:(q.attachments||[]).map((a:any)=>a.id)})','showEditDialog("질문 수정",[{key:"title",label:"질문 제목",value:q.title||""},{key:"body",label:"질문 내용",type:"textarea",value:q.body||""}],async v=>{await action("app_update_question",{p_question:Number(q.id),p_subject:q.subject||"전체",p_title:v.title,p_body:v.body,p_files:(q.attachments||[]).map((a:any)=>a.id)})})');
s=s.replace('const x=window.prompt("메시지를 수정하세요.",m.text||m.body||"");if(x!==null){await rpc("app_update_message",{p_message:Number(m.id),p_text:x,p_files:(m.attachments||[]).map((a:any)=>a.id));location.reload()}}','showEditDialog("메시지 수정",[{key:"text",label:"메시지 내용",type:"textarea",value:m.text||m.body||""}],async v=>{await rpc("app_update_message",{p_message:Number(m.id),p_text:v.text,p_files:(m.attachments||[]).map((a:any)=>a.id));location.reload()})');
fs.writeFileSync(f,s);
