const fs = require('fs');
const path = require('path');
const file = path.join(process.cwd(), 'app', 'page.tsx');
let s = fs.readFileSync(file, 'utf8');

const homeRe = /\{active===\"🏠 홈\"&&[\s\S]*?\}\s*\{active===\"📤 숙제 내기\"/;
const home = `{active===\"🏠 홈\"&&<><section className=\"hero\"><h2>오늘의 영어 문장</h2><div className=\"daily-english\"><b>{dailyEnglish[0]}</b><p>{dailyEnglish[1]}</p></div></section><div className=\"grid\"><Stat label=\"제출할 숙제\" value={assignedTasks.length} icon=\"📝\"/><Stat label=\"내가 낸 숙제\" value={createdTasks.length} icon=\"📤\"/><Stat label=\"완료\" value={assignedTasks.filter((t:any)=>(t.statusByUser?.[me]||\"미제출\")==\=\"완료\").length} icon=\"✅\"/><Stat label=\"새 알림\" value={notifications.filter((n:any)=>!n.read).length} icon=\"🔔\"/></div><section className=\"card\"><div className=\"section-title\"><div><h2>⏰ 가장 임박한 숙제</h2><p className=\"muted\">마감일이 가까운 숙제 3개입니다.</p></div><button className=\"outline\" onClick={()=>setActive(\"📥 숙제 제출\")}>숙제 제출로 이동</button></div><UpcomingTasks tasks={assignedTasks} users={users} me={me}/></section></>} {active===\"📤 숙제 내기\"`;
if (!s.includes("function HomeDashboard")) {\n  if (!homeRe.test(s)) throw new Error("home block not found");\n  s = s.replace(homeRe, home);\n}

const daily = `const DAILY_ENGLISH: [string,string][]=[
  ["Although the policy was intended to reduce inequality, its effects varied considerably depending on the circumstances in which it was implemented.","그 정책은 불평등을 줄이기 위한 것이었지만, 그것이 시행된 상황에 따라 그 효과는 상당히 달랐다."],
  ["What appears at first to be a straightforward solution may create unforeseen difficulties when applied to a more complicated situation.","처음에는 간단해 보이는 해결책이 더 복잡한 상황에 적용되면 예상하지 못한 어려움을 만들어 낼 수도 있다."],
  ["Rather than accepting the evidence simply because it supports a familiar explanation, researchers must consider whether alternative interpretations can account for the same results.","연구자들은 익숙한 설명을 뒷받침한다는 이유만으로 증거를 받아들이기보다, 다른 해석도 같은 결과를 설명할 수 있는지를 고려해야 한다."],
  ["The fact that a particular method has worked effectively in the past does not necessarily mean that it will produce the same outcome under different conditions.","특정 방법이 과거에 효과적으로 작동했다는 사실이 다른 조건에서도 같은 결과를 낳는다는 것을 반드시 의미하는 것은 아니다."],
  ["People tend to overlook information that conflicts with what they already believe, even when that information deserves closer examination.","사람들은 이미 자신이 믿고 있는 것과 충돌하는 정보가 더 면밀히 검토될 가치가 있을 때조차 그것을 간과하는 경향이 있다."],
  ["If the assumptions on which an argument is based are left unexamined, a conclusion that seems reasonable may turn out to be less reliable than it initially appeared.","어떤 주장의 근거가 되는 전제들을 검토하지 않은 채 둔다면, 타당해 보이는 결론이 처음에 보였던 것보다 신뢰하기 어려운 것으로 드러날 수 있다."],
  ["It is not necessarily the amount of information available to us that determines the quality of a decision, but how critically we evaluate the information before using it.","결정의 질을 좌우하는 것은 반드시 우리에게 주어진 정보의 양이 아니라, 그 정보를 사용하기 전에 얼마나 비판적으로 평가하느냐이다."],
  ["Even when two explanations appear to describe the same phenomenon, the predictions they make may differ in ways that can be tested by further observation.","두 설명이 같은 현상을 묘사하는 것처럼 보여도, 그것들이 내놓는 예측은 추가적인 관찰을 통해 검증할 수 있는 방식으로 서로 다를 수 있다."],
  ["Because the consequences of a decision may extend beyond the people who make it, evaluating its benefits requires attention to those who are affected indirectly as well.","어떤 결정의 결과가 결정을 내린 사람들을 넘어 확장될 수 있기 때문에, 그 이점을 평가하려면 간접적으로 영향을 받는 사람들에게도 주의를 기울여야 한다."],
  ["The more confidently a claim is presented, the more carefully we should examine the evidence offered in support of it rather than assuming that confidence itself indicates accuracy.","어떤 주장이 확신에 차서 제시될수록, 자신감 자체가 정확성을 의미한다고 가정하기보다 그 주장을 뒷받침하기 위해 제시된 증거를 더욱 주의 깊게 검토해야 한다."]
];
const dailyEnglish: [string,string]=DAILY_ENGLISH[Math.floor(Date.now()/3600000)%DAILY_ENGLISH.length];
`;
if (!s.includes('const DAILY_ENGLISH')) s = s.replace('const MENU =', daily+'const MENU =');

const commentList = `function CommentList({type,target,users,refreshKey=0}:{type:string;target:number;users:any[];refreshKey?:number}){const[comments,setComments]=useState<any[]>([]);useEffect(()=>{let live=true;rpc(\"app_list_comments\",{p_type:type,p_target:Number(target)}).then(d=>{if(!live)return;const a=Array.isArray(d)?d:arr(d,[\"comments\",\"data\"]);setComments(a)}).catch(()=>{if(live)setComments([])});return()=>{live=false}},[type,target,refreshKey]);return <div className=\"comments-list\">{comments.length?comments.map((c:any)=><div className=\"comment\" key={c.id}>↳ {userLabel(users.find((u:any)=>u.id===(c.userId||c.user_id)))}: {c.text||c.body||\"\"}</div>):<div className=\"muted smalltext\">아직 댓글이 없습니다.</div>}</div>}
`;
if (!s.includes('function CommentList')) s = s.replace('function CreatedTaskList', commentList+'function CreatedTaskList');

const createdRe = /function CreatedTaskList\([\s\S]*?\nfunction Calendar/;
const created = `function CreatedTaskList({tasks,users,refresh}:{tasks:any[];users:any[];refresh?:()=>Promise<void>}){const[drafts,setDrafts]=useState<Record<string,string>>({});const[commentTick,setCommentTick]=useState(0);async function addComment(t:any){const text=(drafts[String(t.id)]||'').trim();if(!text)return;try{await rpc(\"app_add_comment\",{p_type:\"task\",p_target:Number(t.id),p_text:text,p_files:[]});setDrafts(v=>({...v,[String(t.id)]:''}));setCommentTick(v=>v+1);await refresh?.()}catch(e:any){window.alert(e?.message||\"댓글 등록에 실패했습니다.\")}}return <section className=\"card\">{tasks.length?tasks.map((t:any)=><details className=\"created-task\" key={t.id}><summary className=\"created-task-summary\"><div><b>{t.title}</b><div className=\"muted smalltext\">과목: {t.subject||\"-\"} · 출제자: {userLabel(users.find((u:any)=>u.id===t.creatorId))} · 마감: {t.due||\"-\"}</div></div></summary><div className=\"created-task-detail\"><div className=\"task-desc\">{t.desc||t.description||\"내용 없음\"}</div><AttachmentList attachments={t.attachments}/><div className=\"smalltext\"><b>수행 대상 및 상태</b></div>{(t.assigneeIds||[]).map((uid:string)=><div className=\"assignee-status\" key={uid}><span>☐ {userLabel(users.find((u:any)=>u.id===uid))}</span><span className={\"badge \"+statusClass(t.statusByUser?.[uid]||\"미제출\")}>{t.statusByUser?.[uid]||\"미제출\"}</span></div>)}<div className=\"comments-block\"><b>댓글</b><CommentList type=\"task\" target={Number(t.id)} users={users} refreshKey={commentTick}/><input value={drafts[String(t.id)]||\"\"} placeholder=\"댓글 작성 후 Enter\" onChange={e=>setDrafts(v=>({...v,[String(t.id)]:e.target.value}))} onKeyDown={e=>{if(e.key===\"Enter\"&&!e.shiftKey){e.preventDefault();addComment(t)}}}/></div></div></details>):<Empty text=\"내가 낸 숙제 없습니다.\"/>}</section>}
function Calendar`;
if (!createdRe.test(s)) throw new Error('created task block not found');
s = s.replace(createdRe, created);

const calendarRe = /function Calendar\([\s\S]*?\nfunction Chat/;
const calendar = `function Calendar({month,setMonth,events,users}:{month:Date;setMonth:(d:Date)=>void;events:any[];users:any[]}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const[selected,setSelected]=useState<any|null>(null);return <><section className=\"card calendar\"><div className=\"cal-head\"><button onClick={()=>setMonth(new Date(y,m-1,1))}>‹</button><h2>{y}년 {m+1}월</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}>›</button></div><div className=\"week\">{[\"일\",\"월\",\"화\",\"수\",\"목\",\"금\",\"토\"].map(x=><b key={x}>{x}</b>)}</div><div className=\"days\">{Array.from({length:first+days},(_,i)=>i<first?null:i-first+1).map((d,i)=><div className=\"day\" key={i}>{d&&<><span>{d}</span>{events.filter((e:any)=>String(e.due||e.date||\"\").endsWith(\"-\"+String(d).padStart(2,\"0\"))).slice(0,3).map((e:any,j:number)=><button type=\"button\" className=\"calendar-event\" key={e.id||j} onClick={()=>setSelected(e)}>{e.title||\"일정\"}</button>)}</>}</div>)}</div></section>{selected&&<div className=\"modal-backdrop\" onClick={()=>setSelected(null)}><div className=\"modal-card\" onClick={e=>e.stopPropagation()}><button className=\"modal-close\" onClick={()=>setSelected(null)}>×</button><h2>{selected.title||\"숙제\"}</h2><div className=\"info-row\"><span>과목</span><b>{selected.subject||\"-\"}</b></div><div className=\"info-row\"><span>출제자</span><b>{userLabel(users.find((u:any)=>u.id===selected.creatorId))}</b></div><div className=\"info-row\"><span>마감</span><b>{selected.due||\"-\"}</b></div>{selected.status&&<div className=\"info-row\"><span>내 상태</span><b>{selected.status}</b></div>}<div className=\"task-desc\">{selected.description||selected.desc||\"내용 없음\"}</div><button className=\"primary\" onClick={()=>setSelected(null)}>닫기</button></div></div>}</>}
function Chat`;
if (!calendarRe.test(s)) throw new Error('calendar block not found');
s = s.replace(calendarRe, calendar);

s = s.replace('<CreatedTaskList tasks={createdTasks} users={users}/>', '<CreatedTaskList tasks={createdTasks} users={users} refresh={refresh}/>');
s = s.replace('<Calendar month={month} setMonth={setMonth} events={calendar}/>', '<Calendar month={month} setMonth={setMonth} events={calendar} users={users}/>');

s = s.replace('{(q.comments||[]).map((c:any)=><div className=\"comment\" key={c.id}>↳ {c.name||c.user_id}: {c.body}</div>)}', '<CommentList type=\"question\" target={Number(q.id)} users={users}/>');

const upcoming = `function UpcomingTasks({tasks,users,me}:{tasks:any[];users:any[];me:string}){const list=[...tasks].filter((t:any)=>t.due).sort((a:any,b:any)=>String(a.due).localeCompare(String(b.due))).slice(0,3);return list.length?<div className=\"upcoming-list\">{list.map((t:any)=>{const status=t.statusByUser?.[me]||\"미제출\";return <div className=\"upcoming-item\" key={t.id}><div><b>{t.title}</b><div className=\"muted smalltext\">{t.subject||\"-\"} · {t.due}</div><div className=\"muted smalltext\">출제자: {userLabel(users.find((u:any)=>u.id===t.creatorId))}</div></div><span className={\"badge \"+statusClass(status)}>{status}</span></div>})}</div>:<Empty text=\"마감일이 지정된 숙제가 없습니다.\"/>}\n`;
if (!s.includes('function UpcomingTasks')) s = s.replace('function Stat(', upcoming+'function Stat(');

fs.writeFileSync(file, s);
